/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.appCadDelta.Gui;

import br.com.appCadDelta.JPAConttroller.CidadeJpaController;
import br.com.appCadDelta.entity.Cidade;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiquel
 */
public class CadCidadeJInternalFrame extends javax.swing.JInternalFrame {

    private DefaultListModel<Cidade> listModelCidade;
    private Cidade cidade;
    private boolean newCidade =true;

    /**
     * Creates new form CadCidadesJInternalFrame
     */
    public CadCidadeJInternalFrame() {
        listModelCidade = new DefaultListModel<Cidade>();
        CidadeJpaController cidadeJpa = new CidadeJpaController();
        for (Cidade c : cidadeJpa.findAll()) {
            listModelCidade.addElement(c);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListCidade = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jTextCep = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jListCidade.setModel(listModelCidade);
        jListCidade.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCidadeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListCidade);

        jLabel1.setText("Cidade");

        jLabel2.setText("CEP");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RS", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RO", "RR", "SC", "SP", "SE", "TO " }));

        jLabel3.setText("UF");

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cadastro de cidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextCidade)
                            .addComponent(jTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNovo)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cleanField() {
        jTextCep.setText("");
        jTextCidade.setText("");
        jComboBox1.setSelectedIndex(0);
    }

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        boolean erroCidade, erroCep;

        if (jTextCidade.getText().equals("")) {
            erroCidade = true;
            jTextCidade.setBackground(Color.YELLOW);
        } else {
            jTextCidade.setBackground(Color.white);
            erroCidade = false;
        }
        if (jTextCep.getText().equals("")) {
            erroCep = true;
            jTextCep.setBackground(Color.YELLOW);
        } else {
            jTextCep.setBackground(Color.white);
            erroCep = false;
        }

        if (erroCidade == false && erroCep == false) {
            if (newCidade) {
                CidadeJpaController cidadeJpa = new CidadeJpaController();
                cidade = new Cidade();
                cidade.setUf(jComboBox1.getSelectedItem().toString());
                cidade.setNome(jTextCidade.getText());
                cidade.setCep(jTextCep.getText());
                cidadeJpa.create(cidade);
                listModelCidade.addElement(cidade);
                jListCidade.setModel(listModelCidade);
                JOptionPane.showMessageDialog(null, "Cidade cadastrada com sucesso!");
                cleanField();
            } else {
                CidadeJpaController cidadeJpa = new CidadeJpaController();

                cidade.setUf(jComboBox1.getSelectedItem().toString());
                cidade.setNome(jTextCidade.getText());
                cidade.setCep(jTextCep.getText());
                cidadeJpa.edit(cidade);
                JOptionPane.showMessageDialog(null, "Cidade editada com sucesso!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos para cadastrar uma cidade!");
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jListCidadeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCidadeValueChanged
        // TODO add your handling code here:
        newCidade = false;
        cidade = (Cidade) jListCidade.getSelectedValue();
        if (cidade != null) {
            jTextCidade.setText(cidade.getNome());
            jTextCep.setText(cidade.getCep());
            jComboBox1.setSelectedItem(cidade.getUf());
        }
    }//GEN-LAST:event_jListCidadeValueChanged

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        newCidade = true;
        cleanField();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        System.out.println("cidade" + cidade.getNome());
        System.out.println("cidade id = " + cidade.getId());

        CidadeJpaController cidadeJpa = new CidadeJpaController();
        cidadeJpa.delete(cidade);
        listModelCidade.removeElement(cidade);
        jListCidade.setModel(listModelCidade);
        cleanField();
        JOptionPane.showMessageDialog(null, "Cidade removida com sucesso!");

    }//GEN-LAST:event_jButtonDeleteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListCidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCep;
    private javax.swing.JTextField jTextCidade;
    // End of variables declaration//GEN-END:variables
}
