/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.appCadDelta.Gui;

import br.com.appCadDelta.JPAConttroller.CidadeJpaController;
import br.com.appCadDelta.JPAConttroller.ClienteJpaController;
import br.com.appCadDelta.entity.Cidade;
import br.com.appCadDelta.entity.Cliente;
import br.com.appCadDelta.util.CidadeModel;
import br.com.appCadDelta.util.FormataCpf;
import br.com.appCadDelta.util.SessionDesktop;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiquel
 */
public class CadClienteJInternalFrame extends javax.swing.JInternalFrame {

    private DefaultListModel listModel;
    private DefaultComboBoxModel<CidadeModel> comboBoxCidades;
    private Cliente cliente;
    private Cidade cidade;
    private boolean newCliente = true;
    private FormataCpf formataCpf;

    /**
     * Creates new form CadClienteJInternalFrame
     */
    public CadClienteJInternalFrame() {
        listModel = new DefaultListModel();
        ClienteJpaController clienteJpa = new ClienteJpaController();
        for (Cliente c : clienteJpa.findAllT()) {
            listModel.addElement(c);
        }
        comboBoxCidades = new DefaultComboBoxModel<CidadeModel>();
        comboBoxCidades.addElement(null);

        CidadeModel cidadeModelInit = new CidadeModel();
        Cidade cidade = new Cidade();
        cidade.setNome("");
        cidade.setId(0);
        cidadeModelInit.setCidade(cidade);

        CidadeJpaController cidadeJpa = new CidadeJpaController();
        for (Cidade c : cidadeJpa.findAll()) {
            CidadeModel cidadeModel = new CidadeModel();
            cidadeModel.setCidade(c);
            comboBoxCidades.addElement(cidadeModel);
        }
        initComponents();
        formataCpf = new FormataCpf();
        jTextCpf.setDocument(formataCpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextRg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextTelefoneProfissional = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCelular = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextEndereco = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de clientes");

        jList1.setModel(listModel);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Nome");

        jLabel2.setText("RG");

        jLabel3.setText("CPF");

        jLabel4.setText("Telefone");

        jLabel5.setText("Tel Profissional");

        jLabel6.setText("Celular");

        jTextEndereco.setColumns(20);
        jTextEndereco.setRows(5);
        jScrollPane2.setViewportView(jTextEndereco);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/appCadDelta/img/clienteIcon.png"))); // NOI18N
        jLabel8.setText("Cadastro de Clientes");

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Endereço");

        jComboBox1.setModel(comboBoxCidades);

        jLabel7.setText("Cidade");

        jButton4.setText("add OS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("pesquisa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(64, 64, 64)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                            .addComponent(jTextNome)
                                            .addComponent(jTextRg)
                                            .addComponent(jTextCpf)
                                            .addComponent(jTextTelefone)
                                            .addComponent(jTextTelefoneProfissional))))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextTelefoneProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        boolean errorTextNome;

        if (jTextNome.getText().equals("")) {
            errorTextNome = true;
        } else {
            errorTextNome = false;
            jTextNome.setBackground(Color.WHITE);
        }

        if (errorTextNome) {
            jTextNome.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(null, "É necessário informar o nome do Cliente ao sistema!");
        } else {
            if (newCliente) {
                Cliente c = new Cliente();
                c.setNome(jTextNome.getText());
                c.setCpf(jTextCpf.getText());
                c.setRg(jTextRg.getText());
                c.setEndereco(jTextEndereco.getText());
                c.setCelular(jTextCelular.getText());
                c.setTelefone(jTextTelefone.getText());
                c.setTelefoneProfissional(jTextTelefoneProfissional.getText());
                ClienteJpaController clienteJpa = new ClienteJpaController();
                clienteJpa.create(c);
                cleanFields();
                
                listModel.insertElementAt(c, 0);

                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");

            } else {
                ClienteJpaController clienteJpa = new ClienteJpaController();
                cliente.setNome(jTextNome.getText());
                cliente.setCpf(jTextCpf.getText());
                cliente.setRg(jTextRg.getText());
                cliente.setEndereco(jTextEndereco.getText());
                cliente.setCelular(jTextCelular.getText());
                cliente.setTelefone(jTextTelefone.getText());
                cliente.setTelefoneProfissional(jTextTelefoneProfissional.getText());

                CidadeModel cidadeModel = comboBoxCidades.getElementAt(jComboBox1.getSelectedIndex());

                cliente.setCidadeId(cidadeModel.getCidade());

                clienteJpa.edit(cliente);
                JOptionPane.showMessageDialog(null, "Cliente editado com sucesso!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        newCliente = false;

        if (jList1.getSelectedValue() != null) {

            if (jList1.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente!");
            } else {
                cliente = (Cliente) listModel.get(jList1.getSelectedIndex());

                cidade = cliente.getCidadeId();

                if (cidade == null) {
                 jComboBox1.setSelectedIndex(0);
                    System.out.println("ciadade null");
                } else {

                    for (int i = 0; i < comboBoxCidades.getSize(); i++) {
                        CidadeModel cidadeModel = comboBoxCidades.getElementAt(i);

                        if (cidadeModel != null) {
                            if (cidade.equals(cidadeModel.getCidade())) {
                                jComboBox1.setSelectedItem(cidadeModel);
                            }
                        }else{
                            jComboBox1.setSelectedIndex(0);
                        }
                    }

                    System.out.println("ciadade " + cidade.getNome());
                }

                jTextNome.setText(cliente.getNome());
                formataCpf.i = 0;
                jTextCpf.setText(cliente.getCpf());
                formataCpf.i = 1;

                jTextRg.setText(cliente.getRg());
                jTextEndereco.setText(cliente.getEndereco());
                jTextCelular.setText(cliente.getCelular());
                jTextTelefone.setText(cliente.getTelefone());
                jTextTelefoneProfissional.setText(cliente.getTelefoneProfissional());
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    public void cleanFields() {
        jTextNome.setText("");
        jTextCpf.setText("");
        jTextRg.setText("");
        jTextEndereco.setText("");
        jTextCelular.setText("");
        jTextTelefone.setText("");
        jTextTelefoneProfissional.setText("");
        jComboBox1.setSelectedIndex(0);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        newCliente = true;
        JOptionPane.showMessageDialog(null, "Preencha todos os campos para inserir um novo cliente!");
        cleanFields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SessionDesktop.setFlagCliente(1);
        if (jList1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente para cadastrar uma OS!");
        } else {
            Cliente c = (Cliente) listModel.get(jList1.getSelectedIndex());
            SessionDesktop.setCliente(c);
            System.out.println("cliente    === " + c.getNome());

            this.dispose();
            CadOsJInternalFrame cadOs = new CadOsJInternalFrame();
            cadOs.setVisible(true);
            Desktop.getDesktopPane().add(cadOs);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog("Digite o nome do cliente: ");
        ClienteJpaController jpaController = new ClienteJpaController();
        listModel = new DefaultListModel();
        for (Cliente c : jpaController.findByName(name)) {
            listModel.addElement(c);
        }

        jList1.setModel(listModel);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (cliente != null) {

            if (cliente.getId() != null) {
                ClienteJpaController osJpa = new ClienteJpaController();
                osJpa.delete(cliente);
                listModel.removeElement(cliente);
                jList1.setModel(listModel);
                JOptionPane.showMessageDialog(null, "Os removida com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "É>>>>>>>>>>>>>>> preciso selecionar um cliente OS para remove-lo");

            }
        } else {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente para remove-lo");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextCpf;
    private javax.swing.JTextArea jTextEndereco;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextRg;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JTextField jTextTelefoneProfissional;
    // End of variables declaration//GEN-END:variables
}
