/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.appCadDelta.Gui;

import br.com.appCadDelta.JPAConttroller.PecasJpaController;
import br.com.appCadDelta.entity.Peca;
import br.com.appCadDelta.util.LimitadorMoeda;
import br.com.appCadDelta.util.SessionDesktop;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author maiquelknechtel
 */
public class CadPecasJInternalFrame extends javax.swing.JInternalFrame implements WindowListener {

    private DefaultListModel<Peca> listModel = null;
    private Peca peca;
    private boolean newPeca = true;

    /**
     * Creates new form CadPecasJInternalFrame
     */
    public CadPecasJInternalFrame(String os) {
        super("Cadastro de peças OS = "+os);
        listModel = new DefaultListModel<Peca>();
        PecasJpaController pecasCtl = new PecasJpaController();
        List<Peca> listPecas = pecasCtl.findByAparelho(SessionDesktop.getAparelho().getContador());
        LimitadorMoeda limitador = new LimitadorMoeda();

        for (Peca op : listPecas) {
            listModel.addElement(op);
        }
        initComponents();
        jTextValor.setDocument(limitador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jList1.setModel(listModel);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Descricao");

        jButton1.setText("salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextValor)
                                .addGap(55, 55, 55))
                            .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButtonDelete))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:

        if (jList1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,"É preciso selecionar uma peça para poder remove-la!");
        } else {
            PecasJpaController pecaCtl = new PecasJpaController();
            pecaCtl.delete(peca);
            listModel.removeElement(peca);
            jTextDescricao.setText("");
            jTextValor.setText("");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextDescricao.setText("");
        jTextValor.setText("0,00");
        newPeca = true;
        JOptionPane.showMessageDialog(null, "Insira uma nova peça.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (newPeca) {
            peca = new Peca();
            peca.setIdAparelho(SessionDesktop.getAparelho().getContador());
            peca.setDescricao(jTextDescricao.getText());
            if (!jTextValor.getText().equals("")) {
                Double vlrOrcamento = Double.parseDouble(jTextValor.getText().replace(",", "."));
                peca.setValor(vlrOrcamento);
            }

            PecasJpaController pecasCtl = new PecasJpaController();
            pecasCtl.create(peca);
            listModel.addElement(peca);
            jList1.setModel(listModel);
            System.out.println("do -> data base" + peca.getIdAparelho());
        } else {
            peca.setIdAparelho(SessionDesktop.getAparelho().getId());
            peca.setDescricao(jTextDescricao.getText());
            if (!jTextValor.getText().equals("")) {
                Double vlrOrcamento = Double.parseDouble(jTextValor.getText().replace(",", "."));
                peca.setValor(vlrOrcamento);
            }
            PecasJpaController pecasCtl = new PecasJpaController();
            pecasCtl.edit(peca);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        newPeca = false;

        if (jList1.getSelectedValue() != null) {
            peca = listModel.get(jList1.getSelectedIndex());

            jTextDescricao.setText(peca.getDescricao());

            if (peca.getValor() != null) {
                String valorOrcamento = peca.getValor().toString().replace(".", ",");
                String[] vlr = valorOrcamento.split(",");
                if (vlr[vlr.length - 1].length() == 1) {
                    valorOrcamento = valorOrcamento + "0";
                }
                LimitadorMoeda.i = 0;

                jTextValor.setText(valorOrcamento);
                LimitadorMoeda.i = 0;
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void formWindowClosing(java.awt.event.ActionEvent evt) {

        CadOsJInternalFrame cadOs = new CadOsJInternalFrame(SessionDesktop.getOs1().getId());
        Desktop.getDesktopPane().add(cadOs);
        cadOs.setVisible(true);
        System.out.println("Fechando a janela");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {

    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
