/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.appCadDelta.Gui;

import br.com.appCadDelta.JPAConttroller.UsuarioJpaController;
import br.com.appCadDelta.entity.Usuario;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiquel
 */
public class CadUsuarioInternalFrame extends javax.swing.JInternalFrame {

    private DefaultListModel<Usuario> listModelUsuario;
    private boolean newUsuario = true;
    private Usuario usuario;

    /**
     * Creates new form CadUsuarioInternalFrame
     */
    public CadUsuarioInternalFrame() {
        listModelUsuario = new DefaultListModel<Usuario>();
        UsuarioJpaController usuarioJpa = new UsuarioJpaController();
        for (Usuario u : usuarioJpa.findAll()) {
            listModelUsuario.addElement(u);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de usários");

        jList1.setModel(listModelUsuario);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jList1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jList1VetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("login");

        jTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Senha");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuário", "Administrador" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cadastro de usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(3, 3, 3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(jTextNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextLogin, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButtonNovo)
                            .addComponent(jButtonDelete))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLoginActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean errorNome, errorLogin, errorSenha;

        if (jTextLogin.getText().equals("")) {
            errorLogin = true;
            jTextLogin.setBackground(Color.YELLOW);
        } else {
            errorLogin = false;
            jTextLogin.setBackground(Color.WHITE);
        }

        if (jTextNome.getText().equals("")) {
            errorNome = true;
            jTextNome.setBackground(Color.YELLOW);
        } else {
            errorNome = false;
            jTextNome.setBackground(Color.WHITE);
        }

        if (jPasswordField.getText().equals("")) {
            errorSenha = true;
            jPasswordField.setBackground(Color.YELLOW);
        } else {
            errorSenha = false;
            jPasswordField.setBackground(Color.WHITE);
        }

        if (errorNome == false && errorLogin == false && errorSenha == false) {

            if (newUsuario) {
                Usuario u = new Usuario();
                u.setLogin(jTextLogin.getText());
                u.setNome(jTextNome.getText());
                u.setSenha(jPasswordField.getText());
                u.setPerfil(jComboBox1.getSelectedIndex());
                UsuarioJpaController usuarioJpa = new UsuarioJpaController();
                usuarioJpa.create(u);
                cleanFieldUsuario();
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
                listModelUsuario.addElement(u);
                jList1.setModel(listModelUsuario);
            } else {
                
                usuario.setLogin(jTextLogin.getText());
                usuario.setNome(jTextNome.getText());
                usuario.setSenha(jPasswordField.getText());
                usuario.setPerfil(jComboBox1.getSelectedIndex());
                UsuarioJpaController usuarioJpa = new UsuarioJpaController();
                usuarioJpa.edit(usuario);
                JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!");

            }
        } else {
            JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void cleanFieldUsuario() {
        jTextLogin.setText("");
        jTextNome.setText("");
        jPasswordField.setText("");
        jComboBox1.setSelectedIndex(0);
    }

    private void jList1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jList1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1VetoableChange

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        usuario = (Usuario) jList1.getSelectedValue();
//        System.out.println("usuario "+usuario);
        if (usuario != null) {
            jTextLogin.setText(usuario.getLogin());
            jTextNome.setText(usuario.getNome());
            jPasswordField.setText(usuario.getSenha());
            jComboBox1.setSelectedIndex(usuario.getPerfil());

        }
        newUsuario = false;
    }//GEN-LAST:event_jList1ValueChanged

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        System.out.println("delete");
        UsuarioJpaController usuarioJpa = new UsuarioJpaController();
        usuarioJpa.delete(usuario);
        listModelUsuario.removeElement(usuario);
        jList1.setModel(listModelUsuario);
        cleanFieldUsuario();
        JOptionPane.showMessageDialog(null, "Usuario removido com sucesso!");

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        newUsuario = true;
        JOptionPane.showMessageDialog(null, "Preencha todos os campos para inserir um novo usuário!");
        cleanFieldUsuario();
    }//GEN-LAST:event_jButtonNovoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
}
