/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.appCadDelta.Gui;

import br.com.appCadDelta.JPAConttroller.OrdemServicoJpaController;
import br.com.appCadDelta.chart.BarChartDemo1;
import br.com.appCadDelta.entity.Ordemservico;
import br.com.appCadDelta.util.Util;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiquel
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        super(">_ Sistema de controle de ordem de serviço");
//        try {
//            UIManager.setLookAndFeel(
//        UIManager.getCrossPlatformLookAndFeelClassName());
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
//        }

        initComponents();
        setSize(1024, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuDataSaida = new javax.swing.JMenuItem();
        jMenuDataEntrada = new javax.swing.JMenuItem();
        jMenuBuscaPorOs = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setForeground(new java.awt.Color(204, 204, 255));
        jDesktopPane1.setLayout(null);

        jMenu1.setText("File");

        jMenuItem1.setText("Ordem de Servico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cadastro de clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu5.setText("Consulta OS");

        jMenuDataSaida.setText("por data de saida");
        jMenuDataSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataSaidaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuDataSaida);

        jMenuDataEntrada.setText("por data de entrada");
        jMenuDataEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDataEntradaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuDataEntrada);

        jMenuBuscaPorOs.setText("por OS");
        jMenuBuscaPorOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscaPorOsActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuBuscaPorOs);

        jMenuItem9.setText("por Cliente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenu1.add(jMenu5);

        jMenuItem3.setText("Cadastro de usuários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu3.setText("Livro caixa");

        jMenuItem7.setText("Os por dia");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenu6.setText("Grafico");

        jMenuItem10.setText("por ano");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenu1.add(jMenu6);

        jMenuItem5.setText("Cadastro de cidades");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CadOsJInternalFrameSwap cadOs = new CadOsJInternalFrameSwap();
        jDesktopPane1.add(cadOs);
        cadOs.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        CadClienteJInternalFrame cadCliente = new CadClienteJInternalFrame();
        jDesktopPane1.add(cadCliente);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CadUsuarioInternalFrame cadUsuario = new CadUsuarioInternalFrame();
        jDesktopPane1.add(cadUsuario);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "Você deseja realmente sair do sistema ?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        CadCidadeJInternalFrame cadCidade = new CadCidadeJInternalFrame();
        jDesktopPane1.add(cadCidade);
        cadCidade.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        String str = null;
        boolean erro = false;
        try {
            str = JOptionPane.showInputDialog(null, "Digite a data da saída da ordem de serviço:");
            Util.sringToDate(str);
        } catch (Exception p) {
            erro = true;
        }
        if (!erro) {
            CaixaJInternalFrame caixa = new CaixaJInternalFrame(str);
            jDesktopPane1.add(caixa);
            caixa.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Data inválida");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuDataSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataSaidaActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(null, "Digite a data de saida da OS");
        Date date = null;
        boolean errorDateSaida = false;

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            date = formatter.parse(str);

        } catch (ParseException ex) {
            errorDateSaida = true;
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!errorDateSaida) {

            OrdemServicoJpaController osJpa = new OrdemServicoJpaController();
            List<Ordemservico> listOrdemServico = osJpa.findAparelhosBydataSaida(date);
            CadOsJInternalFrame cadOs = new CadOsJInternalFrame(listOrdemServico);
            jDesktopPane1.add(cadOs);
            cadOs.setVisible(true);

            System.out.println(listOrdemServico.size());
        } else {
            JOptionPane.showMessageDialog(null, "Data Inválida!");
        }
        System.out.println("aqui >>" + date);
    }//GEN-LAST:event_jMenuDataSaidaActionPerformed

    private void jMenuDataEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDataEntradaActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(null, "Digite a data de Entrada da OS");
        Date date = null;
        boolean errorDateEntrada = false;

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            date = formatter.parse(str);

        } catch (ParseException ex) {
            errorDateEntrada = true;
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!errorDateEntrada) {

            OrdemServicoJpaController osJpa = new OrdemServicoJpaController();
            List<Ordemservico> listOrdemServico = osJpa.findAparelhosBydataEntrada(date);
            CadOsJInternalFrame cadOs = new CadOsJInternalFrame(listOrdemServico);
            jDesktopPane1.add(cadOs);
            cadOs.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Data Inválida!");
        }


    }//GEN-LAST:event_jMenuDataEntradaActionPerformed

    private void jMenuBuscaPorOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscaPorOsActionPerformed
        // TODO add your handling code here:
        String str = JOptionPane.showInputDialog(null, "Digite o numero da O.S:");
        boolean erroParse = false;
        Integer id = null;

        try {

            id = Integer.parseInt(str);
        } catch (NumberFormatException ex) {
            erroParse = true;
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!erroParse) {

            CadOsJInternalFrame cadOs = new CadOsJInternalFrame(id);
            jDesktopPane1.add(cadOs);
            cadOs.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "ID Inválida!");
        }


    }//GEN-LAST:event_jMenuBuscaPorOsActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        String str = JOptionPane.showInputDialog(null, "Digite o nome do cliente:");

        CadOsJInternalFrame cadOs = new CadOsJInternalFrame(str);
        jDesktopPane1.add(cadOs);
        cadOs.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        String ano = JOptionPane.showInputDialog("Digite o ano que deseja para gerar o gráfico:");
        boolean errorParse = false;
        try {
            Integer.parseInt(ano);
        } catch (NumberFormatException e1) {
            e1.printStackTrace();
            errorParse = true;
        }
        if (!errorParse) {
            BarChartDemo1 bar = new BarChartDemo1(ano);
            bar.setVisible(true);
            jDesktopPane1.add(bar);
            bar.pack();
        }else{
            JOptionPane.showMessageDialog(null, "Entrada inválida!");
        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    public static JDesktopPane getDesktopPane() {
        return jDesktopPane1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscaPorOs;
    private javax.swing.JMenuItem jMenuDataEntrada;
    private javax.swing.JMenuItem jMenuDataSaida;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
